USE [master]
GO

/****** Object:  Database [EmployeesSystem]    Script Date: 10/28/2019 1:51:57 PM ******/
CREATE DATABASE [EmployeesSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeesSystem', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EmployeesSystem.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EmployeesSystem_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EmployeesSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EmployeesSystem] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeesSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeesSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmployeesSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmployeesSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmployeesSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmployeesSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmployeesSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmployeesSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeesSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeesSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeesSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmployeesSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmployeesSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeesSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmployeesSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeesSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmployeesSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeesSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeesSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeesSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeesSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeesSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmployeesSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeesSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [EmployeesSystem] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeesSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeesSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeesSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeesSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EmployeesSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeesSystem] SET  READ_WRITE 
GO


